name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.73.0
        # OPTIONAL: Specify a platform version
        # platform_version: 22.04
        # OPTIONAL: Specify a toolset
#         toolset: gcc
        # OPTIONAL: Specify an architecture
#         arch: x86
    
    # NOTE: If a boost version matching all requirements cannot be found,
    # this build step will fail
    
    - name: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.8 

    - name: build
      run:  whoami  |
            cmake -S . -B Gpufit-build/ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
            
    - name: make
      run:  cmake --build Gpufit-build/ --target all

    - name: Performance test
      run:  ./Gpufit-build/Gpufit_Cpufit_Performance_Comparison
      
    - name: Boost tests
      run:  ./Gpufit-build/test_all.sh
